### ISSUE TITLE
Micro and Macro implications notebook is corrupted

### ISSUE THREAD

**Issue by mnwhite** [econ-ark/DemARK#2]
The first "assignment" notebook was corrupted with merge conflict notations on the commit entitled "Micro-and-Macro update".  I suggest we roll back that commit.

**Comment by llorracc** [comment]
OK; please roll back the commit.  

I'm not sure what changed, or how the file got corrupted, partly because a diff is unwieldy because I forgot to "clear" everything before posting.

I know I'm supposed to remember to "clear" everything before posting, but that's hard to do.  

This will be one of the advantages of moving to the Sphinx/rst workflow (if that works out).

**Comment by mnwhite** [comment]
Will do.  I don't know what happened either.  The only hint is that that commit describes itself as having two "parent" commits.
