### ISSUE TITLE
Problem when loading ipynb file from Binder (No module named 'util')

### ISSUE THREAD

**Issue by cohenimhuji** [econ-ark/DemARK#52]
I loaded the jupyter notebook from binder (follow this link: https://mybinder.org/v2/gh/econ-ark/DemARK/master?filepath=notebooks/Micro-and-Macro-Implications-of-Very-Impatient-HHs-Problems.ipynb).
But when i try to run the notebook in my laptop i got the error:  "ModuleNotFoundError: No module named 'util' "

**Comment by MridulS** [comment]
@cohenimhuji you need to download the full repository not just the notebook as util in present in https://github.com/econ-ark/DemARK/tree/master/lib, so the notebook can't find `util`.

if you are familiar with git. You can do `git clone https://github.com/econ-ark/DemARK` or download the full repository using https://github.com/econ-ark/DemARK/archive/master.zip

**Comment by cohenimhuji** [comment]
Dear Meridul,

Thank you very much.

Regards,
Nimrod

**Comment by llorracc** [comment]
@MridulS,

This is something that I've thought we need to fix for a long time: We should strenuously try to avoid setting things up so that notebooks (ESPECIALLY DemARK notebooks) rely unnecessarily on special things tucked away in a directory structure somewhere.  (This is essentially the same issue as with the Roszypal notebook).  

In this particular case, there is only one tiny tool that is being used -- a progress bar that Matt found somewhere and wanted to use to provide a visual signal that the code was actually doing something.  Maybe by now there is some pip-installable tool that could accomplish the same goal, in which case we could add that to the postBuild or requirements or whatever.  But if there's still no "progress bar" tool, we should just drop it.  (This exact problem, with this exact tool, has generated   confusion maybe 10 times that I know of which is probably the tip of an iceberg of cases I don't know of).  

Once you have a proposed solution that works for this particular notebook (either eliminating the progress bar thing, or pip-installing something, or whatever you think is the best approach), please make a PR for me to review.

**Comment by MridulS** [comment]
solved in https://github.com/econ-ark/DemARK/pull/74
