### ISSUE TITLE
NameError: name 'MyTypes' is not defined

### ISSUE THREAD

**Issue by sbenthall** [econ-ark/DemARK#93]
```
$ ipython Alternative-Combos-Of-Parameter-Values.py 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~/projects/econ-ark/DemARK/notebooks/Alternative-Combos-Of-Parameter-Values.py in <module>
    114 
    115 # + {"collapsed": true}
--> 116 for ThisType in tqdm(MyTypes):
    117     ThisType.solve()
    118     ThisType.initializeSim()

NameError: name 'MyTypes' is not defined
```

**Comment by sbenthall** [comment]
This is still broken for me on `master`

**Comment by MridulS** [comment]
This is supposed to be broken as this is an exercise DemARK, students need to define MyTypes. 
Should we move to this out to another repo?

**Comment by llorracc** [comment]
We should modify any exercises like this so that they run without error, which is easy enough by just giving the variables values that students will need to replace with the correct answers.  I've done that with a couple of DemARKs already, but not this one.  @MridulS, could you put some dummy answers in that will prevent it from breaking Travis?
